// Data bagian Arah di Kompas. Ubah teks di sini, bukan di komponen.
export const SPEC={
  start:"2026-10-01",target:"2027-01-01",
  who:"Spesialis saya",
  title:"Business Automation Systems Engineer",
  niche:"Data terpusat dan otomasi laporan untuk UMKM retail dan seller marketplace.",
  goal:"Bekerja di perusahaan dan membangun produk sendiri.",
  focus:"Hubungi 5 bisnis yang masih menyalin laporan penjualan secara manual, lalu catat siapa yang membalas.",
  skills:[
    {n:"Python",i:"term",s:"ok",t:"Terbukti",p:"SOMETHINC"},
    {n:"PostgreSQL",i:"db",s:"ok",t:"Terbukti",p:"Talatee_DataBase"},
    {n:"FastAPI",i:"zap",s:"ok",t:"Terbukti",p:"Talatee_DataBase"},
    {n:"Docker",i:"box",s:"ok",t:"Terbukti",p:"Compose + Pytest"},
    {n:"Next.js",i:"layout",s:"mid",t:"Sebagian",p:"Perlu proyek publik"},
    {n:"n8n",i:"flow",s:"mid",t:"Belum terlihat",p:"Butuh satu alur nyata"},
    {n:"Hermes",i:"bot",s:"no",t:"Belum ada bukti",p:"Butuh satu demo"}
  ],
  money:[
    {key:"klien",n:"Proyek klien",i:"users",md:"Dibayar per proyek",m:[5,2,2],
     who:"Pemilik UMKM, seller marketplace, brand kecil, resto, klinik.",
     offers:["Analisis data produk <small>Rp 1–5 jt</small>","Dashboard bisnis <small>Rp 3–10 jt</small>","Otomasi laporan <small>Rp 5–15 jt</small>","Scraping dan integrasi data <small>Rp 5–15 jt</small>","Konsultasi dan implementasi sistem data <small>Rp 5–15 jt</small>"],
     est:"Rentang harga dari infografikmu. Belum diuji pasar.",
     skills:["Python","PostgreSQL","n8n","Next.js","Power BI"],
     first:["Pilih satu niche dan satu masalah, misalnya laporan penjualan manual.","Hubungi 5 bisnis per minggu dengan satu tawaran spesifik.","Beri proyek pertama dengan harga ramah demi testimoni."],
     risk:"Tidak berulang, dan klien kecil sering menawar atau menambah permintaan.",
     st:["Prospek","Percakapan","Penawaran","Deal"]},
    {key:"kerja",n:"Kerja di perusahaan",i:"brief",md:"Gaji bulanan",m:[3,5,2],
     who:"Perusahaan retail, e-commerce, logistik, fintech, agensi.",
     offers:["Automation Engineer","Business Systems Analyst","Integration Engineer","Backend Developer Python","Data Engineer junior"],
     est:"",skills:["Python","FastAPI","PostgreSQL","API","Docker","Pytest"],
     first:["Beri README tiap repo: masalah, solusi, cara menjalankan.","Tulis satu case study satu halaman dari proyek terkuat.","Lamar 5 posisi per minggu dan catat hasilnya."],
     risk:"Prosesnya lama dan bergantung bukti. Tanpa portofolio mudah tersaring.",
     st:["Lamaran","Wawancara","Tes/tugas","Tawaran"]},
    {key:"retainer",n:"Retainer",i:"repeat",md:"Biaya bulanan tetap",m:[3,4,3],
     who:"Klien proyek yang sistemnya sudah berjalan.",
     offers:["Pemeliharaan dan perbaikan","Monitoring dan notifikasi","Laporan rutin otomatis","Penambahan fitur tiap bulan"],
     est:"",skills:["n8n","FastAPI","PostgreSQL","Docker"],
     first:["Sebelum serah terima proyek, tawarkan paket perawatan.","Tulis batas layanan: apa yang termasuk, waktu respons.","Mulai dengan satu klien, lihat berapa jam yang benar-benar terpakai."],
     risk:"Tanpa batas layanan yang jelas, pekerjaan bisa melebar tanpa tambahan bayaran.",
     st:["Klien aktif","Ditawari","Setuju","Berbayar"]},
    {key:"produk",n:"Produk sendiri",i:"box",md:"Langganan + biaya setup",m:[1,3,5],
     who:"Warung, laundry, bengkel. Nanti klinik dan resto.",
     offers:["Langganan Buku Kas Warung per outlet","Biaya setup sekali bayar","Versi untuk bisnis lain dengan inti yang sama","Paket laporan WhatsApp tambahan"],
     est:"Harga ditentukan setelah ada yang mau membayar.",
     skills:["Next.js","n8n","WhatsApp API","SQLite/PostgreSQL"],
     first:["Pasang di satu warung nyata dan pantau dua minggu.","Kumpulkan 10 umpan balik tertulis.","Tentukan harga dari yang mau dibayar, bukan dari tebakan."],
     risk:"Lama sebelum balik modal, dan pengguna butuh dukungan terus.",
     st:["Calon pengguna","Demo","Uji coba","Berlangganan"]},
    {key:"konten",n:"Konten dan audiens",i:"video",md:"Tidak langsung, jadi mesin prospek",m:[1,2,4],
     who:"Penonton TikTok yang bisa jadi calon klien, perekrut, atau pembeli.",
     offers:["Prospek masuk untuk jalur Klien","Tawaran kerja lewat DM","Template atau toolkit berbayar","Kelas atau workshop kecil untuk UMKM","Sponsor, kalau audiens sudah besar"],
     est:"",skills:["Bercerita","Demo layar","Studi kasus"],
     first:["Satu konten untuk tiap Projek yang selesai: masalah, proses, hasil.","Isi profil dengan satu ajakan jelas, misalnya 'DM untuk otomasi laporan'.","Catat tiap DM yang masuk sebagai prospek."],
     risk:"Lambat dan tidak pasti. Mudah sibuk membuat konten tanpa pernah mendapat prospek.",
     st:["Konten","Pengikut baru","DM masuk","Jadi prospek"]}
  ],
  qs:["Mendukung spesialisku","Bisa dilihat orang sebagai bukti","Selesai sebelum target"],
  rule:"Ragu ganti bidang? Putuskan di tanggal target, dengan bukti dari calon klien."
};

export const EX={
0:[
{t:"Seller skincare: laporan penjualan masih disalin manual",
 sit:"Brand kecil dengan 15 produk di Shopee dan TikTok Shop. Tiap pagi satu staf menyalin data pesanan ke Excel selama sekitar 2 jam, dan stok sering salah hitung.",
 build:"Skrip Python membaca ekspor pesanan harian, menyimpannya ke PostgreSQL, lalu n8n mengirim ringkasan ke WhatsApp pemilik jam 7 pagi.",
 flow:["Wawancara 30 menit: laporan apa yang dilihat pemilik tiap pagi.","Kumpulkan dua minggu contoh file ekspor dari kedua marketplace.","Bersihkan dan simpan ke PostgreSQL.","Hitung penjualan per produk, produk terlaris, dan stok yang hampir habis.","Atur n8n agar ringkasan terkirim otomatis tiap pagi.","Jalankan satu minggu berdampingan dengan cara lama untuk membandingkan."],
 hasil:"Kerja salin manual 2 jam per hari jadi nol. Stok menipis ketahuan sebelum habis.",
 uang:"Paket Otomasi Laporan, kisaran Rp 5–15 jt sekali bayar. Misalnya disepakati Rp 6 jt.",waktu:"Sekitar 2–3 minggu."},
{t:"Restoran dua cabang: tidak tahu menu mana yang menguntungkan",
 sit:"Pemilik hanya melihat total omzet dari kasir. Ia tidak tahu menu apa yang paling laku per cabang atau jam berapa paling sepi.",
 build:"Data kasir (ekspor Excel) masuk ke PostgreSQL, ditampilkan di dashboard Next.js: penjualan harian per cabang, menu terlaris, jam ramai, dan margin per menu bila harga modal diisi.",
 flow:["Minta ekspor kasir tiga bulan terakhir dari kedua cabang.","Rapikan nama menu yang berbeda antar cabang.","Rancang empat grafik yang menjawab pertanyaan pemilik.","Bangun dashboard dan beri akses lewat tautan dengan login.","Latih pemilik membacanya selama 30 menit."],
 hasil:"Pemilik tahu menu apa yang layak dipromosikan dan jam sepi mana yang cocok untuk promo.",
 uang:"Paket Dashboard Bisnis, kisaran Rp 3–10 jt. Misalnya Rp 5 jt.",waktu:"Sekitar 2–4 minggu."},
{t:"Toko elektronik online: memantau harga pesaing",
 sit:"Pemilik mengecek harga pesaing satu per satu setiap hari untuk 30 produk, dan sering terlambat menyesuaikan harga.",
 build:"Skrip Python mengumpulkan harga 30 produk pesaing tiap hari, menyimpannya ke tabel, dan mengirim notifikasi Telegram saat ada pesaing yang lebih murah.",
 flow:["Daftar produk dan tautan pesaing yang dipantau.","Periksa ketentuan tiap situs. Pakai API atau data resmi bila ada.","Bangun pengumpul data dengan jadwal harian.","Simpan riwayat harga untuk melihat tren.","Atur ambang notifikasi, misalnya selisih lebih dari 5 persen."],
 hasil:"Harga disesuaikan lebih cepat, dan pemilik punya riwayat harga untuk keputusan promo.",
 uang:"Paket Scraping dan Integrasi Data, kisaran Rp 5–15 jt. Misalnya Rp 7 jt.",waktu:"Sekitar 2 minggu."}],
1:[
{t:"Satu minggu sebagai Automation Engineer di perusahaan distribusi",
 sit:"Tim gudang menyusun laporan stok manual tiap Jumat, dan 12 orang menunggu laporan itu.",
 build:"Query PostgreSQL ditambah skrip Python yang menghasilkan laporan stok otomatis dan mengirimkannya lewat email.",
 flow:["Senin: bicara dengan tim gudang, catat laporan yang dibutuhkan.","Selasa dan Rabu: tulis query dan skrip.","Kamis: uji dengan data minggu lalu dan bandingkan dengan laporan manual.","Jumat: laporan terkirim otomatis ke 12 orang, lalu tulis dokumentasi."],
 hasil:"Satu pekerjaan mingguan hilang dari tim gudang. Kamu mulai mengerjakan masalah berikutnya.",
 uang:"Gaji bulanan tetap. Besarnya tergantung perusahaan dan kota, jadi cek rentang di lowongan nyata.",waktu:"Berkelanjutan. Di wawancara, tunjukkan repo dan ceritakan satu masalah dari awal sampai akhir."}],
2:[
{t:"Klien skincare setelah laporan berjalan",
 sit:"Bulan kedua, Shopee mengubah format ekspor dan laporan klien error. Tanpa perawatan, klien harus mencarimu dan menunggu.",
 build:"Paket perawatan bulanan: perbaikan error, satu permintaan kecil per bulan, dan pemantauan otomatis yang memberi tahu bila laporan gagal terkirim.",
 flow:["Tawarkan paket sebelum serah terima proyek.","Tulis isi paket dan waktu respons, misalnya balasan dalam satu hari kerja.","Pasang notifikasi gagal di n8n.","Bulan berikutnya, klien minta laporan retur. Hitung sebagai permintaan kecil atau proyek baru."],
 hasil:"Klien tenang, kamu punya pemasukan yang datang tiap bulan.",
 uang:"Contoh hitungan ilustrasi: 5 klien dikali Rp 500 rb sama dengan Rp 2,5 jt per bulan. Angka paketnya kamu tentukan sendiri.",waktu:"Sekitar 2–4 jam per klien per bulan bila sistemnya stabil."}],
3:[
{t:"Warung kelontong memakai Buku Kas Warung",
 sit:"Pemilik mencatat utang dan penjualan di buku tulis, dan baru sadar stok habis saat pembeli menanyakannya.",
 build:"Pemilik mengirim catatan lewat WhatsApp, sistem merapikan ke dashboard, mengirim laporan harian tiap malam, dan memberi peringatan stok menipis.",
 flow:["Kamu memasang dan mengajarkan pemakaian selama 30 menit.","Pemilik mencatat lewat WhatsApp selama dua minggu.","Malam hari laporan harian masuk otomatis.","Kamu mengumpulkan umpan balik dan memperbaiki yang membingungkan."],
 hasil:"Pemilik tahu untung harian dan stok tanpa menghitung manual.",
 uang:"Contoh hitungan ilustrasi: Rp 50 rb per bulan dikali 40 warung sama dengan Rp 2 jt per bulan. Jalur ini baru terasa besar setelah puluhan pengguna, jadi pelajari dulu apakah mereka mau membayar.",waktu:"Pemasangan cepat, tetapi butuh waktu panjang untuk mengumpulkan pengguna."}],
4:[
{t:"Satu video berubah menjadi satu proyek",
 sit:"Kamu baru menyelesaikan laporan otomatis untuk brand skincare dan ingin orang lain tahu.",
 build:"Video 60 detik dari rekaman layar: sebelum, dua jam menyalin manual. Sesudah, laporan datang sendiri ke WhatsApp.",
 flow:["Rekam layar proses dan hasilnya tanpa suntingan rumit.","Tulis ajakan jelas di profil: 'DM untuk otomasi laporan toko'.","Pemilik toko berkomentar 'bisa untuk toko saya?', lalu kamu balas lewat DM.","Obrolan 15 menit, kamu tanya laporan apa yang masih manual.","Tawarkan paket Analisis Data Produk berukuran kecil sebagai proyek pertama."],
 hasil:"Penonton berubah menjadi percakapan, lalu penawaran. Contoh ilustrasi: 10.000 tayangan menghasilkan sekitar 30 komentar, 5 DM, dan 1 percakapan serius. Angka nyata akan berbeda.",
 uang:"Tidak langsung dari konten. Uangnya datang lewat jalur Klien, dan konten hanya membawa prospek.",waktu:"Butuh banyak konten sebelum pola terlihat. Catat tiap DM di penghitung."}]
};

export const MC=[
{desc:"Menyelesaikan satu masalah data atau otomasi untuk satu bisnis, dari analisis sampai sistem berjalan.",
 jobs:["Bersihkan dan rapikan data Excel/CSV","Bangun database PostgreSQL dan dashboard","Otomasi laporan harian ke WhatsApp atau Telegram","Integrasi data Shopee, TikTok Shop, Lazada","Scraper harga pesaing","Rekonsiliasi data kasir dan stok","Analisis produk terlaris dan produk lambat","Pasang n8n untuk alur kerja berulang"],
 val:"Rp 3 juta – 30 juta+ per proyek",note:"Kecil (analisis, laporan sederhana) sekitar Rp 1–5 jt. Menengah (dashboard, otomasi) Rp 3–15 jt. Besar (database terpusat dengan banyak sumber) Rp 15–30 jt+. Perkiraan awal, belum diuji pasar."},
{desc:"Bekerja tetap di perusahaan sebagai Data, BI, atau Automation Engineer.",
 jobs:["Otomasi laporan harian dan mingguan","Dashboard untuk manajemen","Rekonsiliasi data dan integrasi sistem","Analisis data untuk keputusan","Bangun dan rawat pipeline data","Tulis query SQL untuk tim lain","Uji kualitas data dan dokumentasi proses"],
 val:"Rp 5 juta – 20 juta+ per bulan",note:"Bawah untuk posisi junior atau kota kecil, atas untuk pengalaman dan perusahaan besar. Angka ini belum saya periksa ke lowongan nyata, jadi cek di kotamu."},
{desc:"Setelah proyek selesai, kamu tetap merawat sistem agar berjalan dan berkembang.",
 jobs:["Monitoring dan notifikasi gagal","Perbaiki error dan penyesuaian kecil","Cek kualitas data tiap bulan","Laporan rutin dan ringkasan insight","Menyesuaikan saat format marketplace berubah","Satu permintaan fitur kecil per bulan"],
 val:"Rp 1 juta – 5 juta per bulan per klien",note:"Contoh: 5 klien dikali Rp 1 jt sama dengan Rp 5 jt per bulan. Batasi jam layanan. Bila satu klien memakan jauh lebih dari 4 jam sebulan, naikkan paketnya."},
{desc:"Membuat produk yang bisa dijual berkali-kali dan dipakai banyak orang.",
 jobs:["Buku Kas Warung per outlet","SaaS dashboard untuk UMKM","Versi untuk laundry dan bengkel","Template n8n siap pakai","Template laporan Excel atau Sheets","Add-on laporan WhatsApp","Platform analitik sederhana"],
 val:"Rp 99 ribu – 999 ribu per bulan (atau setup + langganan)",note:"Hitungan: Rp 99 rb × 50 pengguna ≈ Rp 5 jt per bulan. Rp 299 rb × 20 pengguna ≈ Rp 6 jt. Warung kecil kemungkinan sensitif harga, jadi uji dulu di harga rendah. Paket Rp 999 rb lebih cocok untuk bisnis banyak cabang."},
{desc:"Membagikan insight, cara kerja, dan hasil proyek untuk membangun kepercayaan dan membawa prospek.",
 jobs:["Tips analisis data dan otomasi","Studi kasus dan behind the project","Edukasi tools (Python, n8n, dll)","Rekaman layar dari masalah sampai hasil","Before dan after sebuah laporan","Cerita perjalanan belajar","Jawab pertanyaan penonton"],
 val:"Audiens → Prospek → Proyek → Retainer → Produk",note:"Ukur dengan empat angka: konten per minggu, DM masuk, percakapan serius, proposal terkirim. Uangnya datang dari jalur lain."}
];
